function data = import_emg(filename, dataLines)
%IMPORTFILE Import data from a text file
%  DATA = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  DATA = IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  data = importfile("C:\Users\valer\OneDrive - Politecnico di Milano\MATLAB\AGREE-Adaptive-Control\onedof_log\1DOF-EMG-2021-02-03-17-23-26.csv", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 03-Feb-2021 17:47:42

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 11);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "FSMMode", "Var4", "Var5", "EMG_elapsed_time_ms", "Channel_1", "Channel_2", "Var9", "Var10", "Var11"];
opts.SelectedVariableNames = ["FSMMode", "EMG_elapsed_time_ms", "Channel_1", "Channel_2"];
opts.VariableTypes = ["string", "string", "double", "string", "string", "double", "double", "double", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "Var4", "Var5", "Var9", "Var10", "Var11"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "Var4", "Var5", "Var9", "Var10", "Var11"], "EmptyFieldRule", "auto");

% Import the data
data = readtable(filename, opts);

end