function AGREE_Manager_Status = importfile(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   AGREE_MANAGER_STATUS = IMPORTFILE(FILENAME) Reads data from text file
%   FILENAME for the default selection.
%
%   AGREE_MANAGER_STATUS = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads
%   data from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   AGREE_Manager_Status = importfile('AGREE-Manager-2020-08-05-15-14-52.csv', 2, 111484);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2020/08/05 15:19:25

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Read columns of data as text:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric text to numbers.
% Replace non-numeric text with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = mat2cell(dataArray{col}, ones(length(dataArray{col}), 1));
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17]
    % Converts text in the input cell array to numbers. Replaced non-numeric
    % text with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1)
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData(row), regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if numbers.contains(',')
                thousandsRegExp = '^[-/+]*\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(numbers, thousandsRegExp, 'once'))
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric text to numbers.
            if ~invalidThousandsSeparator
                numbers = textscan(char(strrep(numbers, ',', '')), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch
            raw{row, col} = rawData{row};
        end
    end
end


%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
AGREE_Manager_Status = table;
AGREE_Manager_Status.J_elapsed_time_ms = cell2mat(raw(:, 1));
AGREE_Manager_Status.J_position_cpt = cell2mat(raw(:, 2));
AGREE_Manager_Status.J_position_rad = cell2mat(raw(:, 3));
AGREE_Manager_Status.J_velocity_rad_s = cell2mat(raw(:, 4));
AGREE_Manager_Status.J_velocity_computed = cell2mat(raw(:, 5));
AGREE_Manager_Status.J_torque_loadcell = cell2mat(raw(:, 6));
AGREE_Manager_Status.T_torque_des = cell2mat(raw(:, 7));
AGREE_Manager_Status.T_torque_feedforward = cell2mat(raw(:, 8));
AGREE_Manager_Status.T_torque_error = cell2mat(raw(:, 9));
AGREE_Manager_Status.T_torque_p = cell2mat(raw(:, 10));
AGREE_Manager_Status.T_torque_i = cell2mat(raw(:, 11));
AGREE_Manager_Status.T_torque_d = cell2mat(raw(:, 12));
AGREE_Manager_Status.T_torque_fb = cell2mat(raw(:, 13));
AGREE_Manager_Status.T_torque_tot = cell2mat(raw(:, 14));
AGREE_Manager_Status.I_position_des_rad = cell2mat(raw(:, 15));
AGREE_Manager_Status.I_stiffness = cell2mat(raw(:, 16));
AGREE_Manager_Status.I_damping = cell2mat(raw(:, 17));

